networks:
  appsare_go:
    name: appsare_go
services:
  apr_go:
    build:
      context: .
      dockerfile: go.prod.dockerfile
    container_name: apr_go
    entrypoint: ["go", "run","main.go"]
    ports:
      - 3000:3000
    working_dir: /var/www/go_src
    networks:
      - appsare_go
